### ISSUE TITLE
Replace occurrences of ChainID with DomainID (global)

### ISSUE THREAD

**Issue by waymobetta** [ChainSafe/chainbridge-core#149]
We have since moved away from using `chainID` in support of the less-confusing `domainID`. As such, all occurrences of `chainID` should be removed, including logs, flag descriptions, etc.

**list:** (not comprehensive)
[example](https://github.com/ChainSafe/chainbridge-core/blob/main/chains/evm/cli/erc20/deposit.go#L33)
[example 2](https://github.com/ChainSafe/chainbridge-core/blob/main/chains/evm/cli/bridge/cancel-proposal.go#L18)
[example 3](https://github.com/ChainSafe/chainbridge-core/blob/main/chains/evm/cli/bridge/query-proposal.go#L18)

## Expected Behavior

`chainID` is replaced with `domainID`

## Current Behavior

`chainID` still lingers in some places

**Comment by P1sar** [comment]
All the renaming have already be done in `develop` branch, since main were used for v1.0.0 SmartContracts.
Please find any chainID occurrences in develop branch and note them here. If no one will be found, close the issue
