### ISSUE TITLE
Define guideline for CLI flag naming and descriptions

### ISSUE THREAD

**Issue by P1sar** [ChainSafe/chainbridge-core#179]
## Implementation details

This is an issue related to a [discussion](https://github.com/ChainSafe/chainbridge-core/discussions/156) focused around standardizing flag names so that we don't use varying flag names/formats for the same flag across CLI commands.

> The crux of the issue: Since the ChainBridge CLI utilizes so many different flags with varying formats for its various commands, it is possible that a user could get confused; for example, target, versus tokenContract, versus token, versus erc20Address. In other words, why are we using 4 different formats for describing a contract address, whether that be a handler, an erc20 or the bridge contract itself? Additionally, using so many different formats looks unprofessional.

Set basic standards for creating CLI flags:
- formatting
- Externally-Owned addresses
- contract addresses
- handlers

[set-burn](https://github.com/ChainSafe/chainbridge-core/blob/main/chains/evm/cli/bridge/set-burn.go#L17-L19)

## Acceptance Criteria

[] Come up with some points about rules of CLI flags and params naming 
[] Everything that is relate to the address should be named as {blabla}Address
[] Other changes based on guide from first point

**Comment by waymobetta** [comment]
Spoke with @MakMuftic , we will post a draft PR next week after `develop` is merged to `main` in order to get feedback from team on proposed flags/descriptions

**Comment by waymobetta** [comment]
Core `develop` branch merged to `main` [last Friday](https://github.com/ChainSafe/chainbridge-core/commit/f34d57d08455499264a170dc73c94fb7077a3b1f) so draft PR can now be started

**Comment by P1sar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainBridge-5ddf0d8ba55a410001d03d8c/issues/ChainSafe/chainbridge-core/179?planning-poker) with ZenHub @waymobetta @MakMuftic @mpetrun5 @nmlinaric @tcar121293 @taha-be
