### ISSUE TITLE
Update ABI constants

### ISSUE THREAD

**Issue by tcar121293** [ChainSafe/chainbridge-core#181]
## Implementation details
Update ABI constants for most recent contracts version(v2)

## Testing details
Deploy v2 contracts and transfer tokens

## Acceptance Criteria
Should successfully transfer tokens from one chain to another

**Comment by P1sar** [comment]
@tcar121293 I didn't notice that you updated only Bridge ABI and bin but we also need to update ERC20Handler and probably  ERC20PresetMinterPauser
