### ISSUE TITLE
Configurable logger writer (datadog)

### ISSUE THREAD

**Issue by mpetrun5** [ChainSafe/chainbridge-core#187]
## Story
As a user
I want to configure logger
So that I can send logs to some remote collector

## Background

Currently, our logger only logs to console or file, but we want to collect
our logs in Datadog.

## Implementation details

Create some ConfigureLogger function that accepts writer that configures zerologs
writer and implement `DatadogLogWriter` that implements Writer interface to 
enable configuring zerolog to send to datadog.
Check if existing implementation already exists.

## Testing details

- unit tests for to check if zerolog logs are rerouted to Writer interface
- Datadog writer unit tests

## Acceptance criteria

- logger writer is configurable
- logs can be sent to Datadog
- unit tests pass

**Comment by P1sar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainBridge-5ddf0d8ba55a410001d03d8c/issues/ChainSafe/chainbridge-core/187?planning-poker) with ZenHub @MakMuftic @mpetrun5 @nmlinaric @tcar121293 @waymobetta
