### ISSUE TITLE
Add godoc to `chains/evm/calls` package

### ISSUE THREAD

**Issue by MakMuftic** [ChainSafe/chainbridge-core#208]
Add godoc to all public functions and interfaces inside `chains/evm/calls` package

## Implementation details

Follow official godoc [guidelines](https://go.dev/blog/godoc)
## Acceptance Criteria

- [ ] All public functions and interfaces inside `chains/evm/calls` package have a godoc

**Comment by P1sar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainBridge-5ddf0d8ba55a410001d03d8c/issues/ChainSafe/chainbridge-core/208?planning-poker) with ZenHub @MakMuftic @mpetrun5 @nmlinaric @tcar121293 @waymobetta

**Comment by itsbobbyzzz168** [comment]
No longer relevant. Closing.
