### ISSUE TITLE
Add unit testing for contract calls

### ISSUE THREAD

**Issue by MakMuftic** [ChainSafe/chainbridge-core#209]
Expand unit tests for contract calls (currently only a _base contract_ is properly tested by unit tests). 
## Implementation details

In most cases, there is no need for testing a bad case, as this error handling has been tested in _base contract_ unit tests. These unit tests should primarily test if provided arguments can be packed as input data for provided method.
## Acceptance Criteria

- [ ] Each defined contract call has a basic positive case unit test

**Comment by P1sar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainBridge-5ddf0d8ba55a410001d03d8c/issues/ChainSafe/chainbridge-core/209?planning-poker) with ZenHub @MakMuftic @mpetrun5 @nmlinaric @tcar121293 @waymobetta
