### ISSUE TITLE
Standardize the logging format for CLI

### ISSUE THREAD

**Issue by MakMuftic** [ChainSafe/chainbridge-core#210]
Standardize the logging format for all CLI commands.
## Implementation details

Currently, more or less each CLI command takes a different approach when logging success and error messages.
We should try to standardize it in a way that the user has a feeling of consistency when using different commands.
## Acceptance Criteria

- [ ] Define guidlines for logging errors and success informational messages inside CLI commands
- [ ] Refactor all CLI commands to reflect defined guidelines

**Comment by P1sar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainBridge-5ddf0d8ba55a410001d03d8c/issues/ChainSafe/chainbridge-core/210?planning-poker) with ZenHub @MakMuftic @mpetrun5 @nmlinaric @tcar121293 @waymobetta
