### ISSUE TITLE
Generated CLI documentation

### ISSUE THREAD

**Issue by MakMuftic** [ChainSafe/chainbridge-core#213]
## Implementation details

Inside `github.com/spf13/cobra/doc`, there is a functionality for generating markdown documentation from the commands tree. It generates a new markdown file for each file (the great thing is that all these files are already linked, and you get UX like you are browsing through some wiki)

My idea was to add it as a new CLI command (`gen-docs` or something like this), but maybe we can implement it as _make_ command - **this is something to investigate**.

Another interesting idea (proposed by @mpetrun5) was to have a CI check if documentation was updated - **also something to investigate**.

**Inside our main README file**, we should create a section "CLI documentation" linked to the root markdown file of generated documentation.

On the implementation side, it is super simple (the example below shows how it would work if we implement it as a CLI command)
```
import (
	"github.com/spf13/cobra/doc"
)

/**
Rest of the CLI cmd code
*/

GenDocsCmd(cmd *cobra.Command, args []string) error {
	err := doc.GenMarkdownTree(cmd.Root(), "./docs")
	if err != nil {
		log.Fatal(err)
	}
}

```
## Acceptance Criteria

- [ ] Implement CLI documentation generation
- [ ] Refactor repo README file to link to CLI generation

**Comment by itsbobbyzzz168** [comment]
No longer relevant. Closing.
