### ISSUE TITLE
Add check if relayer is registered on the bridge contract before relayer starts

### ISSUE THREAD

**Issue by MakMuftic** [ChainSafe/chainbridge-core#219]
Based on [incident investigation](https://www.notion.so/chainsafe/WB-transfer-from-Besu-to-Celo-didn-t-go-thru-3-712766206e8c46cba3b50881471678ce), before relayer starts, there should be a check if the relayer is registered on the chainbridge contract.

## Implementation details

Call bridge contract -> Display error if not registered

## Testing details

Add unit tests

## Acceptance Criteria

- [ ] Add check if relayer is registered on startup
- [ ] Add unit tests
- [ ] Manually test with our stagging setup

**Comment by P1sar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainBridge-5ddf0d8ba55a410001d03d8c/issues/ChainSafe/chainbridge-core/219?planning-poker) with ZenHub @MakMuftic @mpetrun5 @nmlinaric @tcar121293 @waymobetta
