### ISSUE TITLE
Update deposit CLI function with a priority flag

### ISSUE THREAD

**Issue by tcar121293** [ChainSafe/chainbridge-core#233]
To enable users to set priority metadata through deposit CLI command we need to implement --priority flag for the command

## Implementation details
https://docs.google.com/document/d/153ogDxoV7c43Rhb3ThJT3WDmGR-Lq1NwT9_xiaAg4P8/edit

## Testing details
manual/add or update unit and/or e2e tests if posible

## Acceptance Criteria
It is possible to set and use --priority flag in the deposit CLI command

**Comment by P1sar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainBridge-5ddf0d8ba55a410001d03d8c/issues/ChainSafe/chainbridge-core/233?planning-poker) with ZenHub @MakMuftic @mpetrun5 @nmlinaric @tcar121293
