### ISSUE TITLE
Create new event handler to be able to handle priority data

### ISSUE THREAD

**Issue by tcar121293** [ChainSafe/chainbridge-core#234]
## Implementation details

You can create a new handler or update the existing one if it is possible to have this functionality enabled by default. 
https://docs.google.com/document/d/153ogDxoV7c43Rhb3ThJT3WDmGR-Lq1NwT9_xiaAg4P8/edit
## Testing details
add unit tests for the event handler

## Acceptance Criteria

the event handler is able to handle priority metadata received from the chain

**Comment by P1sar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainBridge-5ddf0d8ba55a410001d03d8c/issues/ChainSafe/chainbridge-core/234?planning-poker) with ZenHub @MakMuftic @mpetrun5 @nmlinaric @tcar121293
