### ISSUE TITLE
Create new message handler to handle the priority data

### ISSUE THREAD

**Issue by tcar121293** [ChainSafe/chainbridge-core#235]
Message handler should append the priority metadata at the end of the proposal data
## Implementation details

You can create a new handler or update the existing one if it is possible to have this functionality enabled by default. 
https://docs.google.com/document/d/153ogDxoV7c43Rhb3ThJT3WDmGR-Lq1NwT9_xiaAg4P8/edit
## Testing details

add/update unit tests for the message handler
## Acceptance Criteria

Message handler is able to append priority metadata at the end of the proposal data

**Comment by P1sar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainBridge-5ddf0d8ba55a410001d03d8c/issues/ChainSafe/chainbridge-core/235?planning-poker) with ZenHub @MakMuftic @mpetrun5 @nmlinaric @tcar121293
