### ISSUE TITLE
Pass the priority data to the ITX transactor to choose the right ITX sender

### ISSUE THREAD

**Issue by tcar121293** [ChainSafe/chainbridge-core#236]
The priority metadata should be passed to the ITX transaction
ITX transactor should based on this information set the right priority for the transaction
## Implementation details

Flag should be optional
Flag should be validated across possible options
https://docs.google.com/document/d/153ogDxoV7c43Rhb3ThJT3WDmGR-Lq1NwT9_xiaAg4P8/edit
## Testing details

add/update unit/e2e tests if possible
manual testing
## Acceptance Criteria

The relayer is able to send the transaction (vote) with gas limit/ gas price based on the priority metadata

**Comment by P1sar** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/ChainBridge-5ddf0d8ba55a410001d03d8c/issues/ChainSafe/chainbridge-core/236?planning-poker) with ZenHub @MakMuftic @mpetrun5 @nmlinaric @tcar121293
