### ISSUE TITLE
bridge not working on evm-evm

### ISSUE THREAD

**Issue by ashkanhaghju** [ChainSafe/chainbridge-core#296]
bridge not working after 
1. i deployed bridge , handlers and erc20 token 
2. set admin resource (0x0000000000000000000000000000000000000000000000000000000000000000)
3. mint token for bridge owner token 
4. approve tokens for handlers
5. add handler token to minter(handler contract minter of erc20)
6. set burnable input erc20 for handler 
7. run this command :  
./bridge evm-cli erc20 deposit --url http://localhost:7545 --private-key "bridge owner key" --domain 1 --decimals 18 --amount 1 --priority fast --resource "0x0000000000000000000000000000000000000000000000000000000000000000" --bridge "bridge address" --recipient "other chain account address"
8. decreased my token balance on chain 1 
9. but  not increase my token balance on chain 2 
10. bridge running with my bridge and handler new config 
11. (bridge cant recognize new deposit event (without any log))
chain 1 : eth (ganache:7545)
chain 2 : eth (ganache:7546)

**Comment by waymobetta** [comment]
Hello, is this after following the [deployment guide](https://github.com/ChainSafe/chainbridge-docs/blob/develop/docs/guides/deployment-guide.md)?

When you ran the `deploy` command, did you configure a `setThreshold` number. If so, do you remember what you set for that threshold?
