### ISSUE TITLE
`FetchEventLogs` might return events from forked chains

### ISSUE THREAD

**Issue by LampardNguyen234** [ChainSafe/chainbridge-core#321]
The current [`FetchEventLogs`](https://github.com/ChainSafe/chainbridge-core/blob/b25168d612e77ddc4e489427dd2b78e2a5e9e3b4/chains/evm/calls/evmclient/evm-client.go#L114) function makes a call to the `FilterLogs` function of the ethclient which then calls the `eth_getLogs` RPC method. This RPC returns an array of log events for a range of given blocks. As specified by the docs (on [Infura](https://docs.infura.io/infura/networks/ethereum/json-rpc-methods/eth_getlogs), [QuickNode](https://www.quicknode.com/docs/ethereum/eth_getLogs), [Alchemy](https://docs.alchemy.com/reference/eth-getlogs)), for each event, `eth_getLogs` will also return a field named `removed` indicating if this event is on a re-orged chain. This is, however, not checked by the `FetchEventLogs` function, which might result in events on the forked chain being included as valid deposits.

**Comment by P1sar** [comment]
Hello @LampardNguyen234 thank you for submitting this bug! We have fixed it and closing the issue so.
