### ISSUE TITLE
How to install this repo?

### ISSUE THREAD

**Issue by zydjohnHotmail** [ChainSafe/chainbridge-core#331]
Hello:
I found some tutorial from old version of the repo, the old tutorial seems to be well written, but I found the old version is now in archive mode. Therefore, I want to use the new version, but I found that the new version has no document for installation, the installation link points to the old version.
Does it mean the installation ream the same as the old version of repo?
By the way, I am using Windows 10, as the repo is built using Go language, do I have to install Go run time library in order to install this repo?
Thanks

**Comment by itsbobbyzzz168** [comment]
NA
