### ISSUE TITLE
USDT token Bridging issue

### ISSUE THREAD

**Issue by AqeelKazmi** [ChainSafe/chainbridge-core#345]
I have a running bridge contracts & Dapp with 4 tokens for Polygon and an Other evm chain. All pairs are running fine as they belongs to 18 decimals. But right now i integrated USDT token  which is 6 decimals ..
When i test it, it seems fine from polygon to other Chain:
https://polygonscan.com/tx/0x1f9d1bb3d0b3717920490ea7d34955c647f60ad2a91f8307bf5ae2894bb61b3e
But when tried from OtherChain to Polygon it reverted with success txn:
https://polygonscan.com/tx/0xcf108faa12fa7eaf4d4939429c9f1174683382edfdcbcea7adb4e541cd7d2f3c

I have checked for data Hex inside txn, it seems fine with accurate amount but still txn has error: "Although one or more Error Occurred [execution reverted] Contract Execution Completed"

Please guide me the issue origin as i am not able to get it

**Comment by mpetrun5** [comment]
As a starting point I think the wisest choice would be to decode the error response from the external contract call to the handler. Specifically, the low level data in the `FailedHandlerExecution` event (https://polygonscan.com/tx/0xcf108faa12fa7eaf4d4939429c9f1174683382edfdcbcea7adb4e541cd7d2f3c#eventlog).

I would assume it is a string error thrown by the contract (context https://ethereum.stackexchange.com/questions/76653/how-to-decode-error-response-from-contact) and with that error at least we'll have a bit more context.

**Comment by AqeelKazmi** [comment]
@mpetrun5  
its just ERC20: call failed 
(b'\x08\xc3y\xa0', b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', 2, 'ERC20: call failed')

**Comment by mpetrun5** [comment]
Usually when that is an error depending on the strategy (lock/release,  mint/burn) the error is either the handler doesn't have enough liquidity (lock/release) or on a mint/burn strategy the handler doesn't have permission to mint the token.
I don't have other ideas apart from that

**Comment by AqeelKazmi** [comment]
![image](https://github.com/ChainSafe/chainbridge-core/assets/30657768/ce59d790-975b-4ee4-b3c9-d0de15d32f8f)
yes, its basically lock/release side. & handler has locked funds at polygon side. thats why i am surprised about this

**Comment by AqeelKazmi** [comment]
@P1sar Do you have anything in your mind related to above? Much appreciated

**Comment by AqeelKazmi** [comment]
sorry @mpetrun5 for bothering you again
Instead of usdt as it was 6 decimals i tried with other 18 decimals stable token DAI , but i faced the same issue. Following is the txn link
https://www.oklink.com/polygon/tx/0x0c2dc8f11eb2e3c02b2563a2ce71f0f52bfab8a8b5f79a9d7e6483759193da36?tab=3
so it clearly seems that protocol has some kind of issue with proxy contracts.I am saying this due to the reason that we already have  4 other erc20 18 decimal tokens without proxy & are successfully running on our bridging platform. It kind of now stuck position for us, need your favor on it thanks.

**Comment by mpetrun5** [comment]
What do you mean by proxy contracts?

**Comment by AqeelKazmi** [comment]
so i am just talking about the upgradeable proxy contracts which are right now usdt & dai in my case...I have 4 other simple erc20  contract tokens which are not upgradeable ones and are working totally fine with chainBridge protocol.. So again my question is Does chainBridge protocol has support for upgradeable erc20 proxy contracts?

**Comment by AqeelKazmi** [comment]
just letting you know, for simple non-upgradeable erc20 token we are approving handler address on them and these are working fine...& same is the case for upgradeable ones we are approving handler address on their proxy contract like for DAI we are calling approve from 0x8f3cf7ad23cd3cadbd9735aff958023239c6a063 address, but as i mentioned earlier about erc20:
call failed error on voteProposal

**Comment by mpetrun5** [comment]
> so i am just talking about the upgradeable proxy contracts which are right now usdt & dai in my case...I have 4 other simple erc20 contract tokens which are not upgradeable ones and are working totally fine with chainBridge protocol.. So again my question is Does chainBridge protocol has support for upgradeable erc20 proxy contracts?

It doesn't have any explicit logic for it, but it should still work the same if it points the proxy contract according to EIP897.

**Comment by AqeelKazmi** [comment]
@mpetrun5 can you give me any example of platform which is already using chainBridge with upgradeable erc20 token? it will be helpful as well

**Comment by shoenseiwaso** [comment]
Sorry for jumping in, but could this be gas estimation issue with the proxied tokens? Have you tried this on a test network and did you either see the same issue or not, and/or did you try manually increasing the gas amount on the test network transactions?

**Comment by AqeelKazmi** [comment]
> Sorry for jumping in, but could this be gas estimation issue with the proxied tokens? Have you tried this on a test network and did you either see the same issue or not, and/or did you try manually increasing the gas amount on the test network transactions?

Thanks @shoenseiwaso for your response, ok sure i will also look in this perspective as well

**Comment by itsbobbyzzz168** [comment]
Closing + archiving
