### ISSUE TITLE
Core local run/setup documentation

### ISSUE THREAD

**Issue by P1sar** [ChainSafe/chainbridge-core#55]
In order to dive in new developers
## Implementation details

- [x] 1) Scripts to start local private chains with docker-compose (eth and celo private networks)
- [x] 2) Script or makefile that deploys all the smart contracts and provide with the addresses and balances  (treshold set to 1)
- [x] 3) How to run relayer from existing branch on example
- [x] 4) How to make you first transfer with UI and with CLI  (those guides could be links to existing docs but with some conclusions)

**Comment by waymobetta** [comment]
This issue may be rolled up to be included in #73 whereby we store this core-example local run/setup documentation in Gitbook alongside other ChainBridge/Core/Solidity/Module documentation, perhaps in [guides](https://github.com/ChainSafe/chainbridge-docs/tree/develop/docs/guides) section
