### ISSUE TITLE
EVM <> CELO deployment guide

### ISSUE THREAD

**Issue by P1sar** [ChainSafe/chainbridge-core#58]
In order to guide user thru the process of setting up their own bridges between CELO and EVM we should provide some documents describing this process
## Implementation details

@taha-be and @waymobetta should work on this together
Information should include next chapters:
 - List of acting entities and their description and relations (Relayers, smart contract, chains, nodes)
- Generating Brdige Admin address, rleayer addresses (CLI could be used), topuping them with base currency (ETH for example)
 - Contract deployment and what every param means
 - Setting all up (Register resource, set mintable burnable (if needed)), setting minters, minintg tokens) and why its all needed
 - Link to making deposit docs  done here https://github.com/ChainSafe/chainbridge-core/issues/57
We should write documentation in MarDown so it's easy could be fit in any Doc systems.
I suggest to use https://hackmd.io/ for development, unitll i decide where to store it.

## Testing details

User with minimum bridge background but with some tech skill is able to setup bridge for EVM <> Celo
## Acceptance Criteria

User with minimum bridge background but with some tech skill is able to setup bridge for EVM <> Celo

**Comment by waymobetta** [comment]
This guide can be found within [chainbridge-docs](https://github.com/ChainSafe/chainbridge-docs/blob/develop/docs/guides/deployment-guide.md).
