### ISSUE TITLE
General deployment guide

### ISSUE THREAD

**Issue by P1sar** [ChainSafe/chainbridge-core#71]
Deployment guide that provide all necessary information on about how to deploy bridge with chainbrdige-core
## Implementation details

@taha-be and @waymobetta should work on this together
Information should include next chapters:
 - List of acting entities and their description and relations (Relayers, smart contract, chains, nodes)
 - Using chainbridge-core-example as template for starting new chain  (This is should be discussed with @P1sar )
- We should cover all possible scenarios with all modules (basically there is only 3, evm-celo, evm-evm, substtrate-evm, and they are not much differs only in some deep details)
 - Contract deployment and what every param means
 - Setting all up (Register resource, set mintable burnable (if needed)), setting minters, minintg tokens) and why its all needed
We should write documentation in MarDown so it's easy could be fit in any Doc systems.
I suggest to use https://hackmd.io/ for development, unitll i decide where to store it.
I guess we should have some chapter called Deployments with  3 sub chapters belong to each example

**Comment by waymobetta** [comment]
https://hackmd.io/@jbr/r1Xr5yieF
