### ISSUE TITLE
Documentation general layout

### ISSUE THREAD

**Issue by P1sar** [ChainSafe/chainbridge-core#73]
Think about and create documentation layout for chainbrdige-docs so that it will include chainbrdige-ui docs and chainbrdige-core docs as well and in the same way it should make people aware that chainbrdige-core is current support bridge

**Comment by P1sar** [comment]
we probably should store all docs in chainbridge-doc repo

**Comment by waymobetta** [comment]
Currently:
- migrating our documentation from [chainbridge-docs develop branch](https://github.com/chainsafe/chainbridge-docs/tree/develop) repo into our Gitbook instance
- this instance URL will be: https://chainbridge-docs.chainsafe.io
- @taha-be is awaiting DNS configuration for this subdomain in order for the URL to be active
- layout format is also being discussed amongst the team and will be a continual WIP

**Comment by waymobetta** [comment]
We have a working example currently deployed in gitbook that we can iterate on. Still awaiting DNS configurations and minor design refactors before publishing gitbook pages publicly.
