### ISSUE TITLE
Rename ChanID

### ISSUE THREAD

**Issue by P1sar** [ChainSafe/chainbridge-core#79]
We really should start the discussion about renaming ChainID param in Chainbridge that conflicts with the EIP-155's ChainID and brings a lot of confusion. This param should be renamed in both Chainbridge and Solidity.
## Implementation details

rename chainID to domainID everywhere
docs  and code related to chainbridge core

**Comment by P1sar** [comment]
https://ethereum.stackexchange.com/questions/37533/what-is-a-chainid-in-ethereum-how-is-it-different-than-networkid-and-how-is-it/37536

**Comment by P1sar** [comment]
should be renamed according to the results of the discussion https://github.com/ChainSafe/chainbridge-core/discussions/82

**Comment by waymobetta** [comment]
Fixed in [develop](https://github.com/ChainSafe/chainbridge-core/commit/26449ec369d6309ab7c04388e6a358af48fb267a) but not yet merged with Main.
